### ISSUE TITLE
Formspree phasing out legacy forms that use email address as part of the form action

### ISSUE THREAD

**Issue by morozgrafix** [raviriley/agency-jekyll-theme#10]
### **Is your feature request related to a problem? Please describe.**
Formspree is phasing out legacy forms (email URLs). 

`<form action="https://formspree.io/your@email.com" method="POST">` is considered to be a legacy URL. Newly created forms utilize `form_id` URL path like `<form action="https://formspree.io/f/a_form_id" method="POST">`

### **Describe the solution you'd like**
It may be a good idea to introduce another site configuration variable, for example `formspree_form_path` that will be utilized for contact_me form (relevant files `_config.yml`, `_includes/contact.html` and `assets/js/contact_me.js`)

### **Describe alternatives you've considered** 
None

### **Additional context** 
Formspree articles related to the upcoming change: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam and https://help.formspree.io/hc/en-us/articles/360056076314

**Comment by morozgrafix** [comment]
PR submitted. 

There are also minor trailing whitespace cleanup along with the changes.

**Comment by raviriley** [comment]
Merged
