### ISSUE TITLE
Not supported by GitHub Pages

### ISSUE THREAD

**Issue by Richar-Du** [raviriley/agency-jekyll-theme#12]
I want to use this theme as my github.io blog, however, I received a "Page build warning" email from Github. The details are as follow:
"
The page builds completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "Jekyll-agency", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://docs.github.com/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=310740832&page_build_id=213757460
"
I didn't edit anything in the repository, is there any way to fix this? Or do I have to change to the Github official theme? I really like your theme, I would appreciate it if you would help me solve this problem.

**Comment by raviriley** [comment]
It looks like you didn't set up the theme correctly. You can use any theme on a GitHub Pages site, you do not have to choose from the built-in Pages themes. Click [here](https://github.com/raviriley/agency-jekyll-theme#installation) for instructions on how to install this theme. If you are having trouble, the easiest way to get started is to use the [starter template](https://github.com/raviriley/agency-jekyll-theme#2-using-the-starter-template) which will generate a repo that is ready to deploy to Pages right away.
