### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by Frants1987** [raviriley/agency-jekyll-theme#13]
Hi,
first of all, great theme.
I just wanted to know how to change the font from font-awesome to something else?
Thanks

**Comment by raviriley** [comment]
Thanks!

[Font Awesome](https://fontawesome.com/) is the source for all the **icons** in the theme. 

Are you trying to use a different icon source? If not, what fonts are you trying to change?

**Comment by Frants1987** [comment]
No, not a different icon source but a different font (Lexend Deca).
Currently the fonts are defined in the all.min.css file which is by definition not really readable. It would be nice to define it in the _config.yml.

**Comment by raviriley** [comment]
Got it, added customizable fonts to `style.yml` to the todo list.

**Comment by raviriley** [comment]
@Frants1987 what font are you trying to change that you want customizability for? If you're looking to change things for many fonts, you can use an unminifier on `all.min.css` or other relevant minified files and make the changes that way, using something like [this](https://mrcoles.com/blog/css-unminify/).

**Comment by Frants1987** [comment]
I wanted to change the font of the text blocks and did it as you suggested, unminifying the `all.min.css` and changing the fonts manually.
I just thought it would be more convenient to have a config parameter in one of the yml files.
Btw. the font I use is lexend.deca from google.

**Comment by raviriley** [comment]
Sounds good, I'll leave your suggestion on the to-do list but glad you figured it out!
