### ISSUE TITLE
Able to fork theme and modify, but still use remote theme?

### ISSUE THREAD

**Issue by fmitchell** [raviriley/agency-jekyll-theme#15]
Greetings. I'm trying to remove the 'Portfolio' and 'Clients' section: 

- https://github.com/brightplum/v3
- http://v3.brightplum.com/

I tried forking your theme, then changing `_config.yml` to point to my fork as the remote, but that doesn't seem to work. Is there a way to modify the jekyll layouts for my own use and still use the remote theme functionality?

**Comment by raviriley** [comment]
No need to do any of that. Simply create a custom layout html file in the layouts folder. To remove the portfolio and client sections from the home layout, simply remove the relevant lines:

```
---
layout: default
---
{% include navheader.html %}

{% include services.html %}
{% include portfolio_grid.html %} - delete this line
{% include timeline.html %}
{% include team.html %}
{% include clients.html %} - delete this line
{% include contact.html %}

```
