### ISSUE TITLE
Trying to use basic bootstrap element within the theme with no success

### ISSUE THREAD

**Issue by lakonis** [raviriley/agency-jekyll-theme#17]
Hello, I was using your theme successfuly until I tried to integrate bootstrap accordion in a page. I was able to add the requested and missing scss elements but it looks like the javascript doesn't proceed. I am not sure what info I can give to debug it.

`bundle exec jekyll serve` gives no error

Thank you!

**Comment by raviriley** [comment]
I suggest reading the Bootstrap Accordion [documentation](https://getbootstrap.com/docs/5.0/components/accordion/) for more information on how to integrate it. For example, the linked page states you need the Collapse JavaScript plugin.

**Comment by lakonis** [comment]
thank you. Indeed I followed the bootstrap documentation. However, should I understand that `assets/js/bootstrap.bundle.min.js` doesn't come with all bootstrap plugins, but a selection of them ?
I did add specific scss boodstrap modules (working), but the JS element gives no result (other than the one already included into  the agency template)

**Comment by raviriley** [comment]
Correct, the minified bootstrap files only include what's needed for this theme. You'll need to add additional plugins if you want the accordion to work.
