### ISSUE TITLE
How to get to the code behind the theme

### ISSUE THREAD

**Issue by tolhuinfarmland** [raviriley/agency-jekyll-theme#27]
Hi, thank you for this nice template. I'm starting on github pages and I could use some help. My issue is that now that i'm trying to customize the template, I'm getting stuck. I guess I should try to get to the original code behind the theme, but I need some help to get there. I guess this isn't a specific issue of this theme, but any advice would be appreciated. 
Regards
JIVB

**Comment by rbenitezpagan** [comment]
@tolhuinfarmland this is the theme, you could use the template that implements this theme here: [https://github.com/raviriley/agency-jekyll-theme-starter](https://github.com/raviriley/agency-jekyll-theme-starter)

**Comment by raviriley** [comment]
This is the Jekyll theme that I built from the [original Agency Bootstrap theme](https://startbootstrap.com/theme/agency). If you're trying to use this theme, get started with the starter template that @rbenitezpagan linked.
