### ISSUE TITLE
Introduce backwards compatibility for multiple language support

### ISSUE THREAD

**Issue by raviriley** [raviriley/agency-jekyll-theme#28]
### **Is your feature request related to a problem? Please describe.**
The current implementation of locales is not backwards compatible

### **Describe the solution you'd like**
if statements for every usage of locales, so that if the user has no locales in any of their YAML files everything behaves like it would before the implementation

@rbenitezpagan if you get the chance, could you go in and add the if statements? You know the implementation better than I do since you wrote it.

**Comment by rbenitezpagan** [comment]
@raviriley Yes, I'll work on it. Assign it to me. 👍

**Comment by raviriley** [comment]
Sounds good, thanks @rbenitezpagan!

**Comment by fmitchell** [comment]
Letting you all know that this PR https://github.com/raviriley/agency-jekyll-theme/commit/34e5e8506674657d856e23aca7e1a7392cf4533c broke my site that, I believe, is still dependent on the old structure.

Screenshot: https://share.getcloudapp.com/qGuJPPyb

The menu, middle section, and some other parts don't show up. I'm going to attempt to fix it based on the changes in that PR.
