### ISSUE TITLE
2. Copyright footer and chrome website tag to show custom url and not ".github.io"

### ISSUE THREAD

**Issue by tolhuinfarmland** [raviriley/agency-jekyll-theme#30]
Hi, this is Issue 2: 

I purchased a domain and I would like all references to the site to show my url and not the github.io reference. I've specified the config.yml file "url:" to https://tolhuinfarmland.com/ but it still shows https://tolhuinfarmland.github.io/ in some places.

As in Chrome Tag:
![image](https://user-images.githubusercontent.com/84542747/120109054-28b4c200-c13e-11eb-89e5-ab4975ecab1c.png)

As in copyright:
![image](https://user-images.githubusercontent.com/84542747/120108998-fe630480-c13d-11eb-80a3-8605b7f9fd94.png)

Kind Regards

**Comment by raviriley** [comment]
This is because you commented out the `title: ` attribute in `_config.yml` (line 20). The title attribute sets the title of the website. Because you commented it out, the root URL was chosen instead.

**Comment by tolhuinfarmland** [comment]
Thanks! I confused the "title:" label with the title of the header part.
