### ISSUE TITLE
Gem-based installation seems broken

### ISSUE THREAD

**Issue by damszew** [raviriley/agency-jekyll-theme#43]
**Describe the bug**
When using gem-based instalation page seems to not render `_data` correctly. `remote_theme` works fine.

**To Reproduce**
1. Clone [template repo](https://github.com/raviriley/agency-jekyll-theme-starter).
2. Add `gem "jekyll-agency"` to Gemfile
3. Run `bundle update`
4. In `_config.yml` use gem-based theme:
  ```
  theme: jekyll-agency
  # remote_theme: raviriley/agency-jekyll-theme
  ```
**Expected behavior**
Page should be displayed correctly no matter how theme is installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/61756963/141194426-579228cb-9c48-482f-8f28-db328ed83021.png)
![image](https://user-images.githubusercontent.com/61756963/141194490-c6cd02a8-818b-4670-af83-224f58db4d5b.png)

**Additional context**
Seems like gem is older than what is currently available on `master` branch, It would be great to add some tags or releases to keep track of what data format is expected in which theme version.

**Comment by kpleines** [comment]
I tried to use the agency template to create a jekyll site. But it doesn't work for me. 
I would be pleased if I could get a example site which makes it more easy to use the beautiful template.

**Comment by rbenitezpagan** [comment]
@kpleines non-gem-based option.

https://github.com/raviriley/agency-jekyll-theme-starter

**Comment by raviriley** [comment]
Just updated the gem, thanks for pointing this out!
