### ISSUE TITLE
Custom pages with language support

### ISSUE THREAD

**Issue by BeneHa** [raviriley/agency-jekyll-theme#44]
Hi,

I have a question about the usage of the theme. So far I am editing _data/sitetext.yml to create content. But I want to create some other pages like legal.md based on the page layout. These should also support multiple languages, so I want to create them as yml like the sitetext.yml and not as markdown like the legal.md. Maybe I even want to base them on a custom section in _includes.
How can I do this?

Thanks for your help :)

**Comment by raviriley** [comment]
You can add liquid to `legal.md` and add to sitetext to add multiple languages to the legal page. If you want to include components, you can make legal an HTML page
