### ISSUE TITLE
Local dev environment working great, but Github Pages gives 404

### ISSUE THREAD

**Issue by lukertaylor** [raviriley/agency-jekyll-theme#48]
Hello,

Great template.

Apologies if this is a newbie question.

I thought I was being clever :-)

I cloned https://github.com/raviriley/agency-jekyll-theme.git. Got it working locally. Configured it the way I want and then pushed to my own repository at https://github.com/lukertaylor/lukertaylor.github.io

I was expecting my Github page to appear, but instead got a 404.

I cloned https://github.com/raviriley/agency-jekyll-theme.git so I could get access and modify the CSS.

Am I just doing it wrong?

Luke

**Comment by lukertaylor** [comment]
It was my bad! I hadn't included the following in _config.yml:

plugins:
  - jekyll-remote-theme

**Comment by amanda-tan** [comment]
Is this fixed? I am not seeing the update to _config.yml. Did you mean updates to the gemfile?
