### ISSUE TITLE
How should I create jekyll-scholar file structure ?

### ISSUE THREAD

**Issue by maj3x** [raviriley/agency-jekyll-theme#53]
Actually, I tried to create it, but I always get an error somewhere,it would be great if you add jekyll-scholar support.

Firstly i tried add 'selected article' section on home page i did but something went wrong when i try  redirecting to a different page e.g: blog tab

![image](https://user-images.githubusercontent.com/82279411/198664192-868138f1-5ad3-45b9-bf2d-59c55a38051b.png)

i added to my home page like this;

![image](https://user-images.githubusercontent.com/82279411/198666192-f9032731-4e3f-4873-8a7b-a1886e167f32.png)

but i don't know how to redirect when i want to go to a new page blog tab

![image](https://user-images.githubusercontent.com/82279411/198673702-4d9ff311-b9a1-4984-a6d6-3710f0c12677.png)

![image](https://user-images.githubusercontent.com/82279411/198673945-8f017f26-556f-4d0a-8de8-885434909a1a.png)

Also, the file structure is like this, but I still can't get rid of some errors.

![image](https://user-images.githubusercontent.com/82279411/198675032-5ebcbffc-6eb7-4643-acd9-b81599e38941.png)

![image](https://user-images.githubusercontent.com/82279411/198675066-caf64e30-c23e-40f8-8837-1c76c582e8a0.png)

![image](https://user-images.githubusercontent.com/82279411/198675113-23daa041-1ef3-4b67-8781-c29fb76008c7.png)

**Comment by raviriley** [comment]
Adding a layout to `_layouts` doesn't make the page route available. You need to use your `blog_home` layout in a markdown or html file for the layout to get used.

**Comment by raviriley** [comment]
It also appears based on your error messages that you are missing the theme files.

**Comment by raviriley** [comment]
`jekyll-scholar` doesn't appear to be heavily used so it will not be added at this time, but if there's a demand for it I will reconsider. Please review their docs for how to use it, especially keeping the following in mind:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/8132955/198712576-5dda1c03-a22c-42f4-8e6c-91d8f61f157f.png">
