### ISSUE TITLE
The jekyll-agency theme could not be found. (Jekyll::Errors::MissingDependencyException)

### ISSUE THREAD

**Issue by xuzhuoxi** [raviriley/agency-jekyll-theme#54]
[logs_1.zip](https://github.com/raviriley/agency-jekyll-theme/files/9902681/logs_1.zip)

**Comment by raviriley** [comment]
The gem is definitely available on [RubyGems](https://rubygems.org/gems/jekyll-agency). You likely don't have the gem installed or did not complete the installation correctly.

**Comment by xuzhuoxi** [comment]
I just created a new Github repository, copied all your content into it, and opened Github Pages.
https://github.com/xuzhuoxi/xuzhuoxi2.github.io

**Comment by xuzhuoxi** [comment]
Can't this theme be applied directly on Github Pages?

**Comment by raviriley** [comment]
Copying the repo isn't quite enough, you must also `bundle install` the dependencies. If you'd like an easier way to get started with GitHub Pages, click [here](https://github.com/raviriley/agency-jekyll-theme-starter/generate) to generate a copy from the starter template 👍
