### ISSUE TITLE
Can't this theme be applied directly on Github Pages?

### ISSUE THREAD

**Issue by xuzhuoxi** [raviriley/agency-jekyll-theme#55]
I just created a new Github repository, copied all your content into it, and opened Github Pages.
https://github.com/xuzhuoxi/xuzhuoxi2.github.io [deleted]
https://github.com/xuzhuoxi/PageTest2

Action could not be executed successfully.

[logs_1.zip](https://github.com/raviriley/agency-jekyll-theme/files/9908477/logs_1.zip)
![Pages](https://user-images.githubusercontent.com/15625162/199221764-7e158b4c-abdb-4482-ba22-a5b3434dfda8.PNG)

**Comment by raviriley** [comment]
Copying the repo isn't quite enough, you must also bundle install the dependencies. If you'd like an easier way to get started with GitHub Pages, click [here](https://github.com/raviriley/agency-jekyll-theme-starter/generate) to generate a copy from the starter template 👍
