### ISSUE TITLE
Porfolio .md files connection

### ISSUE THREAD

**Issue by fairliereese** [raviriley/agency-jekyll-theme#6]
Hey, thanks for creating and providing support for this improved version of the theme. 

I'm trying to figure out how the .md files in the _portfolio directory are linked to.... well really anything. 

For reference, I'm trying to allow for similar functionality as the portfolio section with the team section where by clicking on an individual's picture, information text pops up about them. I've gotten pretty close to finishing but I can't figure out how to point the team files to the correct markdown file for each individual. Any insights on this? I've edited the team.html, teaml.scss, and modals.html files thus far.

You can see the changes I've made in my repo (forked from this one) [here](https://github.com/mortazavilab/mortazavilab.github.io).

**Comment by raviriley** [comment]
the .md files in the `_portfolio` directory generate the portfolio grid and its modals. I'm a bit confused about what you are asking:

a `_team` folder that generates a grid just like the portfolio grid?

 or 

a `_team` folder that generates an entry in the Team section for each .md file in `_team`, and when you click that entry it opens a modal?

**Comment by fairliereese** [comment]
Ideally, I'd want a _team folder that includes a markdown-style page that pops up when you click any given member, I think the latter option that you gave. If you want to take a look at the site that I've built from your fork you might get a better sense of what I'd want. https://mortazavilab.github.io/

I have essentially never worked with this stuff so I'm trying to reverse-engineer everything but my luck has run out on trying to figure this out.

**Comment by raviriley** [comment]
I see what you're saying now. I'll take a look at your code. Your site looks great btw!

**Comment by fairliereese** [comment]
Thanks! Let me know if I can answer any questions about what I've attempted thus far.

**Comment by raviriley** [comment]
I sent u a PR, got it all to work :)

**Comment by fairliereese** [comment]
Thank you so much! I really appreciate the help!

**Comment by raviriley** [comment]
> Thank you so much! I really appreciate the help!

No problem! If possible please consider [supporting the theme](https://www.paypal.me/raviriley) :)

**Comment by fairliereese** [comment]
Done! Keep up the good work!

**Comment by raviriley** [comment]
Thank you so much!
