### ISSUE TITLE
Switching default locale to German

### ISSUE THREAD

**Issue by bugtrapper** [raviriley/agency-jekyll-theme#63]
I'd like to change the locale to German (thanks for making this available!)

When I change the locale entry in _config.yml to "de", the entries will be translated as expected, but the portfolio hover effect stops working and the plus icon gets misplaced:
![de](https://user-images.githubusercontent.com/15230672/212627356-2780ad97-9967-4bb9-9738-437e7d8630a0.png)

When I change it to "de-DE" instead, the portfolio hover works, but the navigation bar disappears and everything else is not translated: 
<img width="960" alt="de-DE" src="https://user-images.githubusercontent.com/15230672/212627560-fe9989e5-a337-4363-9f6e-e151c10ddc4e.png">

How do I properly change the locale?

Versions:
liquid 4.0.4
jekyll 4.3.1
jekyll-agency 1.1.0 (via git clone)

**Comment by raviriley** [comment]
@bkfirmen any ideas on what's going on here?

**Comment by raviriley** [comment]
@bugtrapper does everything work normally with the default english locale?

**Comment by bugtrapper** [comment]
@raviriley Yes. `locale: "en"` lets it look as expected. 

If it's any help, `locale: "es"` or `locale: "es-ES"` causes the same problem as setting it to "de" (navigation bar okay, hover doesn't work, plusses misplaced), but - of course - in Spanish.

**Comment by raviriley** [comment]
@bugtrapper is there anything you've changed or configured differently? I wasn't able to reproduce the issue with a fresh install

**Comment by bugtrapper** [comment]
@raviriley No, it's a fresh install (`git clone https://github.com/raviriley/agency-jekyll-theme.git`) with just `bundle install` and the locale changed in the _config.yml.
I just got a fresh install to confirm and can reproduce the error (this time with jekyll 4.3.2).

Maybe some of my gems have different versions? Here's the output from `bundle install`:
```
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Using bundler 2.4.3
Fetching public_suffix 5.0.1
Fetching liquid 4.0.4
Fetching concurrent-ruby 1.2.0
Fetching eventmachine 1.2.7
Fetching http_parser.rb 0.8.0
Fetching ffi 1.15.5
Fetching forwardable-extended 2.6.0
Fetching rb-fsevent 0.11.2
Fetching rexml 3.2.5
Fetching google-protobuf 3.21.12
Fetching mercenary 0.4.0
Fetching colorator 1.1.0
Installing liquid 4.0.4
Installing forwardable-extended 2.6.0
Installing public_suffix 5.0.1
Fetching rouge 4.0.1
Installing mercenary 0.4.0
Installing colorator 1.1.0
Installing rb-fsevent 0.11.2
Fetching safe_yaml 1.0.5
Installing rexml 3.2.5
Installing http_parser.rb 0.8.0 with native extensions
Installing google-protobuf 3.21.12 with native extensions
Installing safe_yaml 1.0.5
Installing eventmachine 1.2.7 with native extensions
Fetching unicode-display_width 2.4.2
Installing concurrent-ruby 1.2.0
Fetching webrick 1.8.1
Fetching pathutil 0.16.2
Installing rouge 4.0.1
Fetching addressable 2.8.1
Fetching kramdown 2.4.0
Installing ffi 1.15.5 with native extensions
Fetching i18n 1.12.0
Installing unicode-display_width 2.4.2
Installing pathutil 0.16.2
Installing i18n 1.12.0
Installing webrick 1.8.1
Installing kramdown 2.4.0
Installing addressable 2.8.1
Fetching terminal-table 3.0.2
Installing terminal-table 3.0.2
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching sass-embedded 1.58.0 (x86_64-darwin)
Installing sass-embedded 1.58.0 (x86_64-darwin)
Fetching jekyll-sass-converter 3.0.0
Installing jekyll-sass-converter 3.0.0
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching listen 3.8.0
Installing listen 3.8.0
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching em-websocket 0.5.3
Installing em-websocket 0.5.3
Fetching jekyll 4.3.2
Installing jekyll 4.3.2
```
(And ruby 3.2.0)

**Comment by avicndugu** [comment]
Hi @raviriley. I will attempt to resolve this. Based on my initial research, I think the bug has 3 parts.

- [x] 1. Show translated German Navbar whether you set the locale to "de" or "de-DE" on  config.yml.
- [x] 2. Show translated content whether you set the locale to "de" or "de-DE" on  config.yml.
- [ ] 3. The portfolio hover effect stops working and the plus icon gets misplaced.

I have resolve the first and second part of the bug. The third part is tricky so I will continue to do some more research on it and hopefully resolve it.
