### ISSUE TITLE
No Index.html?

### ISSUE THREAD

**Issue by th3ass3t** [raviriley/agency-jekyll-theme#66]
I'm very new so using this as an experiment to learn about how git works.

I've cloned the template to make my own page, and started to customize it, but the changes are taking ages to show up after I push them

From my research I believe it's due to a lack of an index.html ... From what I understand, if there isn't an index.html, then the page should pull from README.md, *unless* there's an index.md... well, there is one, but there's also a readme, so perhaps it's getting confused?

**Comment by raviriley** [comment]
Jekyll generates the home page using the `index.md` file. I suggest checking out the [Jekyll](https://jekyllrb.com/) and [Github Pages](https://docs.github.com/en/pages) docs for help, but it sounds like everything is working for you as intended, it's just that GitHub Pages is slow to update your deployed site.

**Comment by raviriley** [comment]
According to the Github Pages documentation, 

> It can take up to 10 minutes for changes to your site to publish after you push the changes to GitHub. 

If it takes longer than an hour, check out [this page](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-jekyll-build-errors-for-github-pages-sites) for help.

**Comment by raviriley** [comment]
@th3ass3t I closed the issue because this is not an issue with this project, but feel free to ask for further pointers here.

**Comment by th3ass3t** [comment]
> @th3ass3t I closed the issue because this is not an issue with this project, but feel free to ask for further pointers here.

Thanks @raviriley - this was my intent by creating the issue - I figured it would get closed once I got a reply.. I didn't expect it to take such a long time to hear back! :)

It does seem to be working properly as intended, but since the template you've provided doesn't include the index.html file, the updates are intermittent at best. I believe that I will need to clone the whole root project vs the template so  that I have access to the index, which will then rebuild the site each time the changes are made, which also provides some better control over the fonts displayed and other more granular customization

**Comment by raviriley** [comment]
@th3ass3t that would work but shouldn't be necessary, as pushing to any file will trigger a deployment.
