### ISSUE TITLE
Contact form not working (even if it says so)

### ISSUE THREAD

**Issue by francescomucio** [raviriley/agency-jekyll-theme#7]
**Describe the bug**
The contact form in my github pages hosted site doesn't work.

**To Reproduce**
go to untitleddata.company form and send a message, the green boxes appears telling that a message is sent, but no email is delivered

**Expected behavior**
I expect a message in my inbox

**Screenshots**
![image](https://user-images.githubusercontent.com/3058143/92240536-11052180-eebd-11ea-9ad3-670d9d03891b.png)

**Comment by raviriley** [comment]
The contact is powered by [Formspree](https://formspree.io/). If it didn't send you an email when you first used the form, it could've gone to your spam. You'll need to sign up on their website to configure the form. Hope this helps!

**Comment by raviriley** [comment]
Closing this issue
